Spatial sound
phaserjs/phaser pull request #6355
Opened 2023-01-20 10:17 UTC by alxwest

Please do not update the README or Change Log, we will do this when we merge your PR.

This PR (delete as applicable)

* Adds a new feature

Describe the changes below:

----

### New Features - Spatial Sound

Spatial sound takes advantage of the Web Audio API (https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Web_audio_spatialization_basics). This allows to configure sounds to come from a specific position or to track objects with x and y properties. Currently this is designed for 2D but could be 3D capable with a few modifications.

* Works only with `WebAudioSound` and `WebAudioSoundManager` and only in 2D (ignores ang changes to Z or Orientation).
* The `WebAudioSoundManager.setAudioDestination` method accepts any object with `x` and `y` properties. If this method is not used in conjunction with the source configuration, it will default to the center of the canvas.
* The `SoundConfig.source` is a new property that allows `WebAudioSound` to be configured in 2D space. The property can be set to either an object with `x` and `y` properties or a `SpatialSoundConfig`. If set to a object `WebAudioSound` will track it's position. If using  `SoundConfig.source` it can be set in the `SoundConfig` parameter when initializing `WebAudioSound` or when calling method `WebAudioSound.play`.

The following are examples of implementing the above.

* Adding a source coordinates on `WebAudioSound` initialization.

```js
var config = {
                source: {x:200, y:100}
             };
var music = this.sound.add('music', config);
```

* Adding a source object on `WebAudioSound.play`

```js
var enemy = this.image.add('tank');
rumbleSound.play({source:enemy});
```

* Adding the destination coordinates on `WebAudioSoundManager.setAudioDestination`

```js
game.sound.setAudioDestination({x:200, y:100});
```

* Adding a destination object on `WebAudioSoundManager.setAudioDestination`

```js
var player = this.image.add('mario');
game.sound.setAudioDestination(player);
```
----

[Examples for the feature can be found here](https://github.com/alxwest/phaser3-examples/tree/spatical-sound/public/src/3.60/audio/Web%20Audio)

* [spatial with destination coordinates.js](https://github.com/alxwest/phaser3-examples/blob/spatical-sound/public/src/3.60/audio/Web%20Audio/spatial%20with%20destination%20coordinates.js)
* [spatial with destination object.js](https://github.com/alxwest/phaser3-examples/blob/spatical-sound/public/src/3.60/audio/Web%20Audio/spatial%20with%20destination%20object.js)
* [spatial with source coordinates.js](https://github.com/alxwest/phaser3-examples/blob/spatical-sound/public/src/3.60/audio/Web%20Audio/spatial%20with%20source%20coordinates.js)
* [spatial with source object.js](https://github.com/alxwest/phaser3-examples/blob/spatical-sound/public/src/3.60/audio/Web%20Audio/spatial%20with%20source%20object.js)

2023-01-23 15:14 UTC, photonstorm requested changes
Thanks for this PR. I'm happy to merge this, but I think it would benefit from a couple of small changes (aside from this listed in the review).

1) Please ensure the panner node is destroyed properly in `WebAudioSoundManager.destroy` method, or it will leak memory.

2) I do wonder if we should only create the spatial panner node in the first place if the user requests it, rather than just making it by default for everyone (when most won't use it).

3) There is are getter/setters for pan, mute, etc in WebAudioSound and it feels like this ought to have an equivalent added too.

2023-01-23 15:14 UTC, photonstorm commented on src/sound/html5/HTML5AudioSoundManager.js
> +
There's no need for this method in here, because it's already in `BaseSoundManager`.

2023-01-23 15:14 UTC, photonstorm commented on src/sound/BaseSoundManager.js
> +     * @since 3.6.0
Please update from 3.6.0 to 3.60.0

2023-01-23 15:14 UTC, photonstorm commented on src/sound/noaudio/NoAudioSoundManager.js
> +
As with HTML5Audio, there's no need for this method.

2023-01-23 15:14 UTC, photonstorm commented on src/sound/webaudio/WebAudioSound.js
> +     * @since 3.6.0
Please update from 3.6.0 to 3.60.0

2023-01-23 15:14 UTC, photonstorm commented on src/sound/webaudio/WebAudioSoundManager.js
> +     * @since 3.6.0
3.60.0

2023-01-23 15:14 UTC, photonstorm commented on src/sound/webaudio/WebAudioSoundManager.js
> +     * @method Phaser.Sound.BaseSoundManager#setAudioDestination
Should be `WebAudioSoundManager` not `BaseSoundManager` (and doesn't need override jsdoc tag)

No need to say 'only WebAudio' because this is the WebAudio class anyway.

Might be worth giving an example of exactly what the x/y coordinates relate to - i.e. which scale?

2023-01-24 10:27 UTC, alxwest commented
> Please ensure the panner node is destroyed properly in WebAudioSoundManager.destroy method, or it will leak memory.

I followed the same logic as stereo panner node (confusingly `pannerNode`) in `WebAudioSound.destroy` `spatialNode` is also destroyed in the same way. I can't see anything in `WebAudioSoundManager.destroy` for the other nodes?

> I do wonder if we should only create the spatial panner node in the first place if the user requests it, rather than just making it by default for everyone (when most won't use it).

As I've designed spatial sound to be initialised in 3 places (new `WebAudioSound`, `WebAudioSound.play`, `WebAudioSoundManager.setAudioDestination`), I've opted for simplicity as chaining the audio nodes becomes convoluted.

NB calling `WebAudioSoundManager.setAudioDestination` without a spatial panner node present on the sounds has no effect.

It might be better to create `2DWebAudioSound` for clarity?

> There is are getter/setters for pan, mute, etc in WebAudioSound and it feels like this ought to have an equivalent added too.

Is it alright to expose `SpatialSoundConfig` instead of the 14 properties, which I feel will bloat the class for properties the majority won't touch?

> Only create the spatial panner node if the audio context supports it (like we check for createStereoPanner in the same way before making that)

Done. 👍

2023-01-31 15:37 UTC, merged

2023-01-31 16:11 UTC, photonstorm commented
Ok I've merged this in and fixed a few issues, thanks.

One thing I've noticed is that the volume fall-off is _incredibly_ tiny. If the destination is say 400x300 and you set the source to just 380x300 then you can barely hear it. Set it at 200x300 and there is complete silence.

I assume this is a result of the defaults for the rolloff and cone angles? Are those the defaults the WebAudio API provides, or did you select them?

2023-02-01 14:00 UTC, alxwest commented
Correct, I corrected that with my branch (while working on my game incorporating 2D sound). I'll summit further PRs on the bugs I found and possible changes needed.

2023-02-01 15:04 UTC, photonstorm commented
Feel free to submit another PR, but just be aware I've modified the code quite a lot since your original one (it's all in the main repo)